### PR TITLE
Fix #11

### LINKED ISSUE #11: Ability to analyze sosreport or foreman-debug
Ability to analyze both kind of log

### PR DESCRIPTION
**Pull request by meteryam**
this pull request addresses #11 (Ability to analyze sosreport or foreman-debug), which it accomplishes by re-creating the sosreport directory structure and creating soft links in the usual locations that point to comparable files with different names in the foreman-debug directory.

it also includes, perhaps, an ungodly number of miscellaneous changes, including (but not limited to) a reorganized layout.

### CODE REVIEW

**Comment by waldirio** [comment]
Hello @meteryam 

Thanks for this PR, I can see this is a huge change (I really appreciate). However, the color approach is something that will not help when downloading the file and opening in a text editor
```
  export GREP_COLORS='ms=01;33'
  echo $1 | egrep --color=always "^|\#" | tee -a $FOREMAN_REPORT
  export GREP_COLORS='ms=01;31'
```

If you would like to remove or change this behavior, for example, adding a flag to enable/disable, than there you are! :-)

Please, let me know what you think.

Best
Waldirio

**Comment by waldirio** [comment]
Hello @meteryam 

Please, let me know if you would like to rebase/update this PR or cancel it.

Thank you!

**Comment by meteryam** [comment]
we can probably cancel it. i suspect that there have been too many changes to both of our branches over the last year to easily merge them.

**Comment by waldirio** [comment]
Hello,

Ok, I'll cancel this from now. Please, feel free to submit your change in the future!

Thank you!!

**Pull request closed without merging**
